// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQWAkzovD8arlFm8Ab_u-iIWAxzHprcI',
    appId: '1:737722506477:web:77d40ec4f752d94ac100e4',
    messagingSenderId: '737722506477',
    projectId: 'curtianapp',
    authDomain: 'curtianapp.firebaseapp.com',
    storageBucket: 'curtianapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbDUbEgpxTrpEAZpUgKUlM_Rhzx7VSc5A',
    appId: '1:737722506477:android:b9e151bc92fdd1ecc100e4',
    messagingSenderId: '737722506477',
    projectId: 'curtianapp',
    storageBucket: 'curtianapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXx4T0qCityTTOtIeKyOesVV-x3fKc3Ug',
    appId: '1:737722506477:ios:1db8100a38fd7033c100e4',
    messagingSenderId: '737722506477',
    projectId: 'curtianapp',
    storageBucket: 'curtianapp.appspot.com',
    iosBundleId: 'com.example.curtianApp',
  );
}
